"""One-shot generator: convert the dayan shutdown PNG into an LVGL v9 L8 image
descriptor as a C source file, for embedding into firmware.

Usage:
    python tools/gen_shutdown_image.py <input.png> <output.c>

The generated C file declares a `lv_image_dsc_t shutdown_image` symbol that can
be used with `lv_image_set_src` on a LVGL v9 image widget.
"""
import sys
from PIL import Image, ImageOps

EPD_W = 176
EPD_H = 264
THRESHOLD = 128  # > white, <= black (EPD is binary)


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)

    src_path, out_path = sys.argv[1], sys.argv[2]
    src = Image.open(src_path).convert("L")

    # Fit-to-height, then letterbox on a 176x264 black canvas (background is
    # already black in the artwork, so the bars are seamless).
    sw, sh = src.size
    scale = EPD_H / sh
    nw = max(1, int(round(sw * scale)))
    nh = EPD_H
    resized = src.resize((nw, nh), Image.LANCZOS)

    canvas = Image.new("L", (EPD_W, EPD_H), color=0)
    if nw <= EPD_W:
        x = (EPD_W - nw) // 2
        canvas.paste(resized, (x, 0))
    else:
        # Source was wider than display after height fit — center-crop.
        x = (nw - EPD_W) // 2
        canvas.paste(resized.crop((x, 0, x + EPD_W, EPD_H)), (0, 0))

    # Threshold to pure black/white so the binary EPD output is crisp.
    binarized = canvas.point(lambda v: 255 if v > THRESHOLD else 0, mode="L")

    data = binarized.tobytes()
    assert len(data) == EPD_W * EPD_H, len(data)

    lines = []
    lines.append("// Auto-generated by tools/gen_shutdown_image.py — do not edit by hand.")
    lines.append("#include \"lvgl.h\"")
    lines.append("")
    lines.append(f"#define SHUTDOWN_IMG_W {EPD_W}")
    lines.append(f"#define SHUTDOWN_IMG_H {EPD_H}")
    lines.append("")
    lines.append("static const uint8_t shutdown_image_data[] = {")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("const lv_image_dsc_t shutdown_image = {")
    lines.append("    .header = {")
    lines.append("        .magic = LV_IMAGE_HEADER_MAGIC,")
    lines.append("        .cf = LV_COLOR_FORMAT_L8,")
    lines.append("        .flags = 0,")
    lines.append(f"        .w = SHUTDOWN_IMG_W,")
    lines.append(f"        .h = SHUTDOWN_IMG_H,")
    lines.append(f"        .stride = SHUTDOWN_IMG_W,")
    lines.append("        .reserved_2 = 0,")
    lines.append("    },")
    lines.append("    .data_size = sizeof(shutdown_image_data),")
    lines.append("    .data = shutdown_image_data,")
    lines.append("    .reserved = NULL,")
    lines.append("    .reserved_2 = NULL,")
    lines.append("};")
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {out_path} ({len(data)} bytes of image data)")


if __name__ == "__main__":
    main()
